### PR TITLE
~/local/bin installation

### LINKED ISSUE #14: link_console_script global install tries to write to /usr/bin
On Unix, global installs of console scripts attempt to write to /usr/bin.

```py
> ~/.local/bin/vpip install -g story
building venv at /home/jayvdb/.vpip/pkg_venvs/story
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-19.3.1
...
link console script 'story'
Traceback (most recent call last):
  File "/home/jayvdb/.local/bin/vpip", line 11, in <module>
    load_entry_point('vpip', 'console_scripts', 'vpip')()
  File "/home/jayvdb/projects/python/vpip/vpip/cli.py", line 57, in cli
    module.run(ns)
  File "/home/jayvdb/projects/python/vpip/vpip/commands/install.py", line 33, in run
    install_global(ns.PACKAGE)
  File "/home/jayvdb/projects/python/vpip/vpip/commands/install.py", line 60, in install_global
    link_console_script(pkg, overwrite=True)
  File "/home/jayvdb/projects/python/vpip/vpip/commands/link.py", line 43, in link_console_script
    linker.dest.unlink()
  File "/usr/lib64/python3.7/pathlib.py", line 1287, in unlink
    self._accessor.unlink(self)
PermissionError: [Errno 13] Permission denied: '/usr/bin/story'
```

The script `story` is already installed in `/home/jayvdb/.vpip/pkg_venvs/story/bin`, and the next step would be to be create a symlink in `/home/jayvdb/.local/bin/` , but instead it is writing to `/usr/bin/` which isnt allowed.

`install.py` includes `# TODO: make pip support install_scripts` which may be referring to some part of this problem.

However the comment also mentions https://github.com/pypa/pip/issues/3934 , which has a recent comment indicating it has been fixed indirectly, but not in a way that helps with a target-scripts-dir different from the target-dir.

I think it is a good idea to let the scripts be installed into the venv as normal, and then copy them to the `GLOBAL_SCRIPT_FOLDER`.  And the global script directory for unix should be `~/.local/bin` rather than `/usr/bin`

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes #14

### CODE REVIEW

**Comment by jayvdb** [comment]
I can be very easily convinced to check the processes effective uid / `/usr/bin/` writable and write to `/usr/bin/` if `vpip` was invoked with permission to install really globally.  Some package managers do that.

**Comment by eight04** [comment]
This is how `pip` builds the bin path. Does the logic work on your side?
https://github.com/pypa/pip/blob/c729a84b4884511912f459f3e340367c2872f495/src/pip/_internal/locations.py#L74-L88

**Comment by jayvdb** [comment]
2am here. Will check that in morning

**Comment by jayvdb** [comment]
That seems quite odd.
```py
>>> import pip._internal.locations
>>> pip._internal.locations.user_site
'/home/jayvdb/.local/lib/python3.7/site-packages'
>>> bin_user
'/home/jayvdb/.local/lib/python3.7/site-packages/bin'
>>> import site
>>> user_site = site.getusersitepackages()
>>> user_site
'/home/jayvdb/.local/lib/python3.7/site-packages'
>>> bin_user = os.path.join(user_site, 'bin')
'/home/jayvdb/.local/lib/python3.7/site-packages/bin'
```
```bash
$ ls /home/jayvdb/.local/lib/python3.7/site-packages/bin
ls: cannot access '/home/jayvdb/.local/lib/python3.7/site-packages/bin': No such file or directory
```

It looks like those are only used in `uninstall` and only when `dist_in_usersite(dist)` is true for the package being uninstalled - my guess is that it is never true.

The real directories used for installation are from `distutils_scheme(..)`

```py
>>> pip._internal.locations.distutils_scheme('foo', user=True)
{'purelib': '/home/jayvdb/.local/lib/python3.7/site-packages', 'platlib': '/home/jayvdb/.local/lib/python3.7/site-packages', 'headers': '/home/jayvdb/.local/include/python3.7m/foo', 'scripts': '/home/jayvdb/.local/bin', 'data': '/home/jayvdb/.local'}
```

The distutils schemes are at https://github.com/python/cpython/blob/master/Lib/distutils/command/install.py#L22 , but afaik the `.local` stuff is only in pip, maybe setuptools, not distutils.

I think trying to emulate pip/setuptools/distutils isnt useful.  I see macOS users regularly complaining that the scripts are located in `$HOME/Library/Python/X.Y/bin` or in `$HOME/.local/bin`.

There doesnt appear to be a user-writable path entry on the default macOS PATH   https://stackoverflow.com/questions/9832770/where-is-the-default-terminal-path-located-on-mac

I would like to ensure that multiple `vpip` can be installed and they dont have algorithms that change depending on the presence of another `vpip`.  So I think always using `~/.local/bin` on Linux is appropriate given it is used by Fedora and RedHat.

We could have a fallback to to see if `~/.bin` already exists and is on the `PATH`.
Also using https://github.com/ofek/userpath can help add entries to the PATH if needed, or like `pip` we could warn if it isnt already on the PATH.

**Comment by jayvdb** [comment]
Rebased only.

**Comment by eight04** [comment]
> I think trying to emulate pip/setuptools/distutils isnt useful. I see macOS users regularly complaining that the scripts are located in `$HOME/Library/Python/X.Y/bin` or in `$HOME/.local/bin`.

Since vpip is a transparent wrapper of pip, I think we should mimic the behavior of pip i.e. reuse the scripts folder created by pip (`distutils_scheme(...)`).

We can try writing to the script folder with `user=False`. If that failed, set `user=True` and try again.

> I would like to ensure that multiple `vpip` can be installed

This is impossible. Currently, we install global packages to `~/.vpip/pkg_venvs`. If you have two instances of vpip, they both write to this directory.

**Comment by jayvdb** [comment]
@eight04 , pip is already using `distutils_scheme(...)` within the venv, and the bin wrappers are in the right spot there.

It sounds like you want to try to mimic pip outside the venv, as if `pip install --user x` was used.  Deferring to pip and distutils on what "global install" means is not how to ensure a "npm-like experience".  distutils have a bunch of config files which determine those locations, and they are not user-friendly.  [Here](https://bouktin.blogspot.com/2012/04/configure-pydistutilscfg-python.html) is a primer on them.  Having global bin wrappers always go into `~/.local/bin` is much easier to describe for users in the documentation.  It doesnt change.  Also not deferring to distutils/pip means that vpip can change the behaviour without needing to consider users who may have fiddled with their `.pydistutils.cfg`, and you dont need to find ways to prevent distutils from finding a `setup.cfg` which contains a custom scheme intended for a single package.

> This is impossible. Currently, we install global packages to ~/.vpip/pkg_venvs. If you have two instances of vpip, they both write to this directory.

That is still predictable behaviour.  That is no different to having two instances of the same `vpip` running at once.

I was referring to using `path.os.dirname(shutil.which("vpip"))` as problematic.

Having one `vpip` install scripts into a directory because it has a different `vpip` in it is not very predictable behaviour.  The problem is the behaviour changes when a new `vpip` appears. `PATH` changes what is executed, not where the data is placed.  e.g. I might have `vpip` in `~/.local/bin`, and my scripts go there.  Then someone installs `vpip` into `/usr/local/bin` or `/usr/bin` and suddenly my `vpip`, even if invoked explicitly as `~/.local/bin/vpip` will try to put scripts somewhere else.  These may not be common scenarios, but it is best to avoid them anyway, otherwise you'll have someone rely on it and you can change it.

**Comment by eight04** [comment]
> distutils have a bunch of config files which determine those locations, and they are not user-friendly.

I think respecting the user config is more user-friendly. If the user wants to customize the destination of the scripts folder, they have to create a pip config or a vpip config (in case we decide to add one). Since pip already handles this as you mentioned, I'd like to avoid the duplication in vpip.

> I was referring to using `path.os.dirname(shutil.which("vpip"))` as problematic.

Yeah, let's drop this idea.

**Comment by jayvdb** [comment]
ok, I'll try to get it working based on the pip/distutils scheme.

**Comment by eight04** [comment]
BTW, I think there will be some problems if vpip itself was installed inside in venv. `distutils_scheme` may return the folder inside venv instead of the global scripts folder. We can fix it later in other PRs.

This PR can focus on generating a valid `GLOBAL_SCRIPT_FOLDER` in a common situation, so we can release a version which is compatible with Linux.

**Comment by jayvdb** [comment]
The common situation is to hard-code it to `~/.local/bin`.  That is what works consistently and matches what people expect pip to do on unix, except in very unusual situations and we have no user requirements gathered for those situations.  `vpip` should be hiding all the complexities of pip+virtualenvs.

**Comment by eight04** [comment]
Are you still working on this? I can try fixing it these days. (Although I can't test it.)

**Comment by jayvdb** [comment]
Sorry, been busy with real work.

**Pull request closed without merging**
